In [1]:
#Install Jupyter notebook and run the first program and share the screenshot of the output
import numpy as np
np.random.seed(0)
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3, 4))
x3=np.random.randint(10,size=(3, 4, 5))
print(x1)
print(x2)
print(x3) 

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [3]:
#Program to find and print all numbers between 2000 and 3200 that are divisible by 7, not a multiple of 5
#Using a string to display the numbers:
# numstr is the string variable to hold the numbers for display.
numstr=''

''' 
Iterate from 2000 to 3201 incrementing the value by 1 every time. 
3201 is used so as to include 3200 as well in the calculation. 
'''

for val in range(2000,3201,1):
    if (val % 7 == 0) and (val % 5 > 0):
        newval=str(val)+','
        numstr=numstr+newval
        
#Remove the comma at the end.
newstr=numstr[:-1]
print('The Numbers between 2000 and 3200 divisible by 7, but not a multiple of 5 are: ',newstr)


The Numbers between 2000 and 3200 divisible by 7, but not a multiple of 5 are:  2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199


In [4]:
#Program to find and print all numbers between 2000 and 3200 that are divisible by 7, not a multiple of 5
#Using a List to hold and display the numbers:
# numstr is the string variable to hold the numbers for display.
numlist=[]

''' 
Iterate from 2000 to 3201 incrementing the value by 1 every time. 
3201 is used so as to include 3200 as well in the calculation. 
'''
for val in range(2000,3201,1):
    if (val % 7 == 0) and (val % 5 > 0):
        numlist.append(val)
print('The Numbers between 2000 and 3200 divisible by 7, but not a multiple of 5 are: ', numlist)

The Numbers between 2000 and 3200 divisible by 7, but not a multiple of 5 are:  [2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [8]:
#Accept the first and last name of the user and print them in the reverse order. 
# Fname gets the first name and Lname gets the last name. 
# Assuming that reverse order means the characters of the first and last are to be reversed. 
Fname=input('Enter your First Name : ')
Lname=input("Enter your Last Name : ")

# Create lists to hold First and Last name characters 
FnameList=list(Fname)
LnameList=list(Lname)

# Reverse the characters in the first and last name. 
FnameList.reverse()
LnameList.reverse()

# String the characters back from the reverse list of first name and reverse list of last name. 
FnameRev=''
LnameRev=''
for char in FnameList:
    FnameRev=FnameRev+char
for char in LnameList:
    LnameRev=LnameRev+char

#Print the reverse of first and reverse of Last name with a space in between
print('The reversed name is: ', FnameRev, LnameRev)


Enter your First Name : Geetha
Enter your Last Name : Nair
The reversed name is:  ahteeG riaN


In [9]:
'''Program to find the volume of a sphere whose diameter is 12cm'''
#Use Math library to get the value of 'pi'
#diam is the variable for diameter, rad is the radius which is half of diameter. 
import math
diam=12
rad=diam/2

# Calculate the volume with the formula given
volume=4/3*math.pi*rad*rad*rad
print('Volume of the Sphere with diametere 12cm is : ', volume)

Volume of the Sphere with diametere 12cm is :  904.7786842338604
